services:
  - type: web
    name: stock-backtest-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    dockerContext:   backend
    # healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=70.0

