services:
  - type: web
    name: stock-backtest-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    dockerContext:   backend
    autoDeploy: true
    # 如果你项目里没启用 actuator，请暂时不要加健康检查
    # healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=70.0
