services:
  - type: web
    name: stock-backtest-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    dockerContext: .
    autoDeploy: true
    # healthCheckPath: /actuator/health  # 有 actuator 再加
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=70.0